name: shared
description: Shared Package - Building Multiple Flutter Applications by Sharing a Common Code Base for Phones, Tablets, Web-Based Apps, and Packages.
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^5.0.1
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
